### ISSUE TITLE
[FileManagerStorage] FileManager 통해 파일 저장하기

### ISSUE THREAD

**Issue by aCafela-coffee** [sero3779/ios-wanted-GyroData#16]
## Description
데이터를 json 파일로 저장하거나 불러옵니다.

## Todo
- [ ] FileManagerStorage 제작

**Comment by sero3779** [comment]
반영해야 할 사항들을 담은 이슈를 만들었으니 해당 이슈는 close하겠습니다.

**Comment by aCafela-coffee** [comment]
Duplicate of #18
